name: Add Issues to TODO list

on: 
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to todo list
    runs-on: ubuntu-latest
    steps:

     - uses: actions/checkout@v3

     - uses: actions/add-to-project@v0.5.0
       with:

        project-url: https://github.com/orgs/Decatur-Robotics/projects/2
        github-token: ${{ secrets.PAT }}

            
