#Node id of project: "PVT_kwDOAJ9aT84AaUJq"
#test pr node id: 'PR_kwDOLB2J4c5kmPKe'

name: Update Pull Request Status to "Awaiting Review"

on: 
  pull_request:
    types: [review_requested]


jobs: 
  update-status-to-review:
    runs-on: ubuntu-latest
    steps:

      - name: Get Project ID of PR
        env:
          PR_ID: ${{ github.event.pull_request.node_id }}
          GH_TOKEN: ${{ secrets.WORKFLOWSAUTH }}



        run: |
          pr_project_id="$( gh api graphql -f prID=$PR_ID -f query='
          query($prID: ID!) {
            node(id: $prID) {
              ...on PullRequest {
                projectItems(first: 1) {
                  nodes {
                    id
                  }
                }
              }
            }
          }'
             )"
            echo 'PR_PROJECT_ID=$pr_project_id' >> GITHUB.ENV



      # - uses: monry/actions-get-project-item-id@v2.0.2
      #   id: get-project-item-id
      #   with:
      #    github-token: ${{ secrets.WORKFLOWSAUTH }}
      #    project-id: 'PVT_kwDOAJ9aT84AaUJq'
      #    issue-id: ${{github.event.pull_request.node_id}}
      # - run: |
      #     echo '${{ steps.get-project-item-id.outputs.project-item-id }}' >> $GITHUB_OUTPUT
      

  

      - uses: kalgurn/update-project-item-status@v0.0.1
        
        with:
          project-url: https://github.com/orgs/Decatur-Robotics/projects/2/views/1
          github-token: ${{ secrets.WORKFLOWSAUTH }}
          item-id: ${{ env.PR_PROJECT_ID }}
          status: "Awaiting Review"





